# Generated by Django 3.2.8 on 2021-10-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mercadopago_access_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mercadopago_public_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mercadopago_refresh_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
