# Generated by Django 3.1.3 on 2020-12-09 03:02

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_first_name', models.CharField(max_length=150)),
                ('billing_last_name', models.CharField(max_length=150)),
                ('billing_address', models.CharField(max_length=300)),
                ('billing_address2', models.CharField(blank=True, max_length=300)),
                ('billing_department', models.CharField(choices=[('AM', 'Amazonas'), ('AN', 'Ancash'), ('AP', 'Apurimac'), ('AR', 'Arequipa'), ('AY', 'Ayacucho'), ('CA', 'Cajamarca'), ('CLL', 'Callao'), ('CU', 'Cusco'), ('HV', 'Huancavelica'), ('HU', 'Huanuco'), ('IC', 'Ica'), ('JU', 'Junin'), ('LL', 'La Libertad'), ('LA', 'Lambayeque'), ('LI', 'Lima'), ('LO', 'Loreto'), ('MD', 'Madre de Dios'), ('MO', 'Moquegua'), ('PA', 'Pasco'), ('PI', 'Piura'), ('PU', 'Puno'), ('SM', 'San Martin'), ('TA', 'Tacna'), ('TU', 'Tumbes'), ('UC', 'Ucayali')], max_length=3)),
                ('billing_province', models.CharField(max_length=50)),
                ('billing_district', models.CharField(max_length=50)),
                ('shipping_first_name', models.CharField(max_length=150)),
                ('shipping_last_name', models.CharField(max_length=150)),
                ('shipping_address', models.CharField(max_length=300)),
                ('shipping_address2', models.CharField(blank=True, max_length=300)),
                ('shipping_department', models.CharField(choices=[('AM', 'Amazonas'), ('AN', 'Ancash'), ('AP', 'Apurimac'), ('AR', 'Arequipa'), ('AY', 'Ayacucho'), ('CA', 'Cajamarca'), ('CLL', 'Callao'), ('CU', 'Cusco'), ('HV', 'Huancavelica'), ('HU', 'Huanuco'), ('IC', 'Ica'), ('JU', 'Junin'), ('LL', 'La Libertad'), ('LA', 'Lambayeque'), ('LI', 'Lima'), ('LO', 'Loreto'), ('MD', 'Madre de Dios'), ('MO', 'Moquegua'), ('PA', 'Pasco'), ('PI', 'Piura'), ('PU', 'Puno'), ('SM', 'San Martin'), ('TA', 'Tacna'), ('TU', 'Tumbes'), ('UC', 'Ucayali')], max_length=3)),
                ('shipping_province', models.CharField(max_length=50)),
                ('shipping_district', models.CharField(max_length=50)),
                ('items', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=300)),
                ('address2', models.CharField(blank=True, max_length=300)),
                ('department', models.CharField(choices=[('AM', 'Amazonas'), ('AN', 'Ancash'), ('AP', 'Apurimac'), ('AR', 'Arequipa'), ('AY', 'Ayacucho'), ('CA', 'Cajamarca'), ('CLL', 'Callao'), ('CU', 'Cusco'), ('HV', 'Huancavelica'), ('HU', 'Huanuco'), ('IC', 'Ica'), ('JU', 'Junin'), ('LL', 'La Libertad'), ('LA', 'Lambayeque'), ('LI', 'Lima'), ('LO', 'Loreto'), ('MD', 'Madre de Dios'), ('MO', 'Moquegua'), ('PA', 'Pasco'), ('PI', 'Piura'), ('PU', 'Puno'), ('SM', 'San Martin'), ('TA', 'Tacna'), ('TU', 'Tumbes'), ('UC', 'Ucayali')], max_length=3)),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
