# Generated by Django 3.0.8 on 2020-07-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200704_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tshirt',
            old_name='status',
            new_name='active',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
