# Generated by Django 3.0.8 on 2020-07-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200705_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tshirt',
            old_name='product_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='store',
            name='base_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
