# Generated by Django 3.0.8 on 2020-07-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200710_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
