# Generated by Django 3.0.8 on 2020-07-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
