# Generated by Django 3.0.8 on 2020-07-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200711_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
            preserve_default=False,
        ),
    ]
