# Generated by Django 3.0.8 on 2020-07-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_store_shipping_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='shipping_price',
            new_name='shipping_cost',
        ),
    ]
